2 target resources
champ-oss/action-mongo-atlas-nuke pull request #3
Opened 2022-10-21 20:56 UTC by atxplangl

2022-10-21 21:01 UTC, jjno91 approved these changes

2022-10-24 19:56 UTC, justin-champtitles requested changes, later dismissed

2022-10-24 19:56 UTC, justin-champtitles commented on action-mongo-atlas-nuke.py
> +    except:
It would be best to check for specific exceptions instead of this blanket `except:`

2022-10-24 19:56 UTC, justin-champtitles commented on action-mongo-atlas-nuke.py
>          raise
I'm not sure what the need here is to catch an exception and then throw another one? You might instead check for specific `status_code` values like 404.

2022-11-04 16:42 UTC, jjno91 approved these changes

2022-11-04 16:45 UTC, merged